CREATE TABLE EMP(
	EMP_ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255),
    DEPT_ID INT
);
    
CREATE TABLE DEPT(
	DEPT_ID INT,
    DEPT_NAME VARCHAR(255)
    );
    
INSERT INTO EMP ( NAME, DEPT_ID) VALUES
	('Ishan', 10),
    ('Aarav', 20),
    ('Tanishq', 30),
    ('Harsh', NULL);

INSERT INTO DEPT (DEPT_ID, DEPT_NAME) VALUES
	(10, 'Sales'),
    (20, 'finance'),
    (40, null);

SELECT * FROM EMP;
SELECT * FROM DEPT;
select EMP.DEPT_ID, EMP.NAME, DEPT.DEPT_NAME FROM EMP INNER JOIN DEPT ON EMP.DEPT_ID = DEPT.DEPT_ID;
select EMP.DEPT_ID, EMP.NAME, DEPT.DEPT_NAME FROM EMP LEFT JOIN DEPT ON EMP.DEPT_ID = DEPT.DEPT_ID;
select EMP.DEPT_ID, EMP.NAME, DEPT.DEPT_NAME FROM EMP RIGHT JOIN DEPT ON EMP.DEPT_ID = DEPT.DEPT_ID;

-- FULL OUTER JOIN DOES NOT SUPPORTS IN MYSQL, TO USE IT WE NEED TO FIRST FIND LEFT JOIN(OR LEFT OUTER JOIN) AND RIGHT JOIN(OR RIGHT OUTER JOIN) AND THEN USE UNION TO COMBINE THEM AND GET THE RESULT