CREATE TABLE DATA (
    NAME VARCHAR(50),
    SALARY INT
);

INSERT INTO DATA VALUES
    ("Sarah", 70000),
    ("Mike", 60000),
    ("David", 50000),
    ("John", 60000),
    ("Alex", 40000);

SELECT NAME, SALARY, ROW_NUMBER() OVER(ORDER BY SALARY DESC) AS avg_salary FROM DATA
SELECT NAME, SALARY, RANK() OVER(ORDER BY SALARY DESC) AS avg_salary FROM DATA
SELECT NAME, SALARY, DENSE_RANK() OVER(ORDER BY SALARY DESC) AS avg_salary FROM DATA 
SELECT NAME, SALARY, NTILE(2) OVER(ORDER BY SALARY DESC) AS bucket FROM DATA



CREATE TABLE EMPLOYEES_1(
    EMP_ID INT PRIMARY KEY,
    NAME VARCHAR(50),
    DEPARTMENT VARCHAR(50),
    SALARY INT
);

INSERT INTO employees_1 VALUES
    (1,"JOHN", "HR", 50000),
    (2,"SARAH", "HR", 60000),
    (3,"MIKE", "IT", 70000),
    (4,"DAVID", "IT", 80000),
    (5,"EMMA", "IT", 75000),
    (6,"ALEX", "IT", 55000),
    (7,"CHRIS", "SALES", 65000),
    (8,"SOPHIA", "SALES", 60000);

SELECT NAME, DEPARTMENT, SALARY, ROW_NUMBER() OVER(ORDER BY SALARY) AS SERIAL_NUMBER FROM employees_1
SELECT NAME, DEPARTMENT, SALARY, DENSE_RANK() OVER(ORDER BY SALARY DESC) AS Rank_number FROM employees_1
SELECT EMP_ID, NAME, DEPARTMENT, SALARY, AVG(SALARY) OVER() AS AVG_SALARY FROM employees_1
SELECT EMP_ID, NAME, DEPARTMENT, SALARY, MAX(SALARY) OVER(ORDER BY SALARY DESC) AS MAXIMUM_SALARY FROM employees_1
SELECT NAME, DEPARTMENT, SALARY, SUM(SALARY) OVER() AS TOTAL_EXPENDITURE FROM employees_1
SELECT NAME, DEPARTMENT, SALARY, NTILE(4) OVER() AS GRP_NUMBER FROM employees_1
SELECT NAME, DEPARTMENT, SALARY, DENSE_RANK() OVER(PARTITION BY DEPARTMENT ORDER BY SALARY) AS _RANK_ FROM employees_1

WITH RANKED_EMPLOYEES AS (
    SELECT NAME, DEPARTMENT, SALARY, DENSE_RANK() OVER(PARTITION BY DEPARTMENT ORDER BY SALARY DESC) AS SALARY_RANK FROM employees_1
)
SELECT NAME, DEPARTMENT, SALARY FROM RANKED_EMPLOYEES WHERE SALARY_RANK = 1

WITH RANKED_EMPLOYEES AS(
    SELECT NAME, DEPARTMENT, SALARY, DENSE_RANK() OVER(PARTITION BY DEPARTMENT ORDER BY SALARY DESC) AS SALARY_RANK FROM EMPLOYEES_1
)
SELECT NAME, DEPARTMENT, SALARY FROM RANKED_EMPLOYEES WHERE SALARY_RANK<=2 ORDER BY DEPARTMENT, SALARY DESC

WITH AVG_SALARY AS (
    SELECT NAME, DEPARTMENT, SALARY, AVG(SALARY) OVER(PARTITION BY DEPARTMENT) AS DEPT_AVG_SALARY FROM EMPLOYEES_1
)
SELECT NAME, DEPARTMENT, SALARY, DEPT_AVG_SALARY FROM AVG_SALARY 

WITH MAX_SALARY AS(
    SELECT NAME, DEPARTMENT, SALARY, MAX(SALARY) OVER(PARTITION BY DEPARTMENT) AS MAXIMUM_SALARY FROM employees_1
)
SELECT NAME, DEPARTMENT, SALARY, MAXIMUM_SALARY FROM MAX_SALARY

WITH TOTAL_SALARY AS(
    SELECT NAME, DEPARTMENT, SALARY, SUM(SALARY) OVER(PARTITION BY DEPARTMENT) AS MAX_SALARY FROM EMPLOYEES_1
)
SELECT NAME, DEPARTMENT, SALARY, MAX_SALARY FROM TOTAL_SALARY 

WITH AVERAGE_SALARY AS(
    SELECT NAME, DEPARTMENT, SALARY, AVG(SALARY) OVER(PARTITION BY DEPARTMENT) AS AVG_SALARY FROM EMPLOYEES_1
)
SELECT NAME, DEPARTMENT, SALARY, AVG_SALARY FROM AVERAGE_SALARY WHERE SALARY > AVG_SALARY

WITH SECOND_HIGHEST AS(
    SELECT NAME, DEPARTMENT, SALARY, DENSE_RANK() OVER(PARTITION BY DEPARTMENT ORDER BY SALARY DESC) AS SECOND_RANK FROM EMPLOYEES_1
)
SELECT NAME, DEPARTMENT, SALARY FROM SECOND_HIGHEST WHERE SECOND_RANK = 2

